sudo: required
services:
  - docker
before_install:
  - docker build -t adaopedro/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true adaopedro/docker-react npm run test -- --coverage
  - echo "Scripts executed successfully!!"