services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "test"]